plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = '1.0.0'
group = 'com.example.cronos'
base { archivesName = 'greenlantern' }

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods { "cronos" { source sourceSets.main } }
        }
        client { property 'forge.enabledGameTestNamespaces', 'cronos' }
        server { property 'forge.enabledGameTestNamespaces', 'cronos'; args '--nogui' }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'
}

tasks.named('jar', Jar).configure {
    manifest.attributes([
        'Specification-Title': 'cronos',
        'Specification-Vendor': 'cronos',
        'Specification-Version': '1',
        'Implementation-Title': 'cronos',
        'Implementation-Version': project.jar.archiveVersion,
        'Implementation-Vendor': 'cronos'
    ])
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }

def flatResDir = new File(layout.buildDirectory.get().asFile, 'flat-resources')

tasks.register('stageResources', Sync) {
    into flatResDir
    from(projectDir) { include 'mods.toml'; into 'META-INF' }
    from(projectDir) { include 'pack.mcmeta' }
}

sourceSets {
    main {
        java {
            srcDirs = [projectDir]
            include 'Cronos*.java'
        }
        resources {
            srcDirs = [flatResDir]
        }
    }
}

tasks.named('processResources').configure { dependsOn 'stageResources' }
