modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="cronos"
version="1.0.0"
displayName="Cronosapiente"
description='''
Mod propio con poderes de control del tiempo: rayos temporales, detener, ralentizar y acelerar el tiempo, retroceso y mas.
'''

[[dependencies.cronos]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cronos]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
