modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="policia"
version="1.0.0"
displayName="Policia"
description='''
Personaje policia con skin propia y un arbol de habilidades que se desbloquea con experiencia. Primera habilidad: escudo balistico.
'''

[[dependencies.policia]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.policia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
