modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="glsolo"
version="1.0.0"
displayName="Solo Linterna Verde (filtro)"
description='''
Oculta en la pestana creativa y en JEI los objetos de Legends Superheroes que no son de Linterna Verde.
'''

[[dependencies.glsolo]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.glsolo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.glsolo]]
    modId="legends_superheroes"
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"
